# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "2026" ]
  pull_request:
    branches: [ "2026" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
        # Build the project
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build the project
        run: dotnet publish Demo.BlazorWasmApp/Demo.BlazorWasmApp.csproj -c Release -o artifacts
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          # Artifact name
          name: # optional, default is github-pages
          # Path of the directory containing the static assets.
          path: artifacts/wwwroot # default is _site/
          # Duration after which artifact will expire in days.
          retention-days: # optional, default is 1
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          # Artifact name
          name: # optional, default is github-pages
          # Path of the directory containing the static assets.
          path: artifacts/wwwroot # default is _site/
          # Duration after which artifact will expire in days.
          retention-days: # optional, default is 1